sudo: required
language: generic

services:
  - docker
before_install:
  - docker build -t alperzafer/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true alperzafer/react-test npm test

after_success:
  - docker build -t alperzafer/mutli-client ./client
  - docker build -t alperzafer/mutli-nginx ./nginx
  - docker build -t alperzafer/mutli-server ./server
  - docker build -t alperzafer/mutli-worker ./worker
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push alperzafer/mutli-client
  - docker push alperzafer/mutli-nginx
  - docker push alperzafer/mutli-server
  - docker push alperzafer/mutli-worker

deploy:
  provider: elasticbeanstalk
  region: us-east-1
  app: mutli-docker
  env: Mutlidocker-env
  bucket_name: elasticbeanstalk-us-east-1-978497795272
  bucket_path: docker_mutli
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY